services:
  sub-backend:
      image: angrydogy/sub-backend
      environment:
        - SCHEME_PATH=scheme.sql
        - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
        - GRPC_PORT=0.0.0.0:8080
        - DEFAULT_PROXY_ADDRESS=127.0.0.1:8000
      network_mode: host
