services:
  sub-backend:
      image: angrydogy/sub-backend
      environment:
        - SCHEME_PATH=scheme.sql
        - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
        - GRPC_PORT=localhost:8080
      depends_on:
        - postgres
  postgres:
      image: postgres:latest
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports: 
        - '5432:5432'

