// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	entity "dev/master/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
}

// Connect mocks base method.
func (m *MockRepository) Connect(source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", source)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockRepositoryMockRecorder) Connect(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockRepository)(nil).Connect), source)
}

// CreateCountry mocks base method.
func (m *MockRepository) CreateCountry(ctx context.Context, name string) (*entity.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCountry", ctx, name)
	ret0, _ := ret[0].(*entity.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCountry indicates an expected call of CreateCountry.
func (mr *MockRepositoryMockRecorder) CreateCountry(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCountry", reflect.TypeOf((*MockRepository)(nil).CreateCountry), ctx, name)
}

// CreateSubscription mocks base method.
func (m *MockRepository) CreateSubscription(ctx context.Context, subscription entity.Subscription) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, subscription)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockRepositoryMockRecorder) CreateSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockRepository)(nil).CreateSubscription), ctx, subscription)
}

// CreateTrialSubscription mocks base method.
func (m *MockRepository) CreateTrialSubscription(ctx context.Context, subscription entity.Subscription) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrialSubscription", ctx, subscription)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrialSubscription indicates an expected call of CreateTrialSubscription.
func (mr *MockRepositoryMockRecorder) CreateTrialSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrialSubscription", reflect.TypeOf((*MockRepository)(nil).CreateTrialSubscription), ctx, subscription)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, userId int64) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userId)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, userId)
}

// FindActiveUsersKeys mocks base method.
func (m *MockRepository) FindActiveUsersKeys(ctx context.Context, userId int64) (map[string]*entity.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveUsersKeys", ctx, userId)
	ret0, _ := ret[0].(map[string]*entity.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveUsersKeys indicates an expected call of FindActiveUsersKeys.
func (mr *MockRepositoryMockRecorder) FindActiveUsersKeys(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveUsersKeys", reflect.TypeOf((*MockRepository)(nil).FindActiveUsersKeys), ctx, userId)
}

// FindCountryByName mocks base method.
func (m *MockRepository) FindCountryByName(ctx context.Context, name string) (*entity.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCountryByName", ctx, name)
	ret0, _ := ret[0].(*entity.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCountryByName indicates an expected call of FindCountryByName.
func (mr *MockRepositoryMockRecorder) FindCountryByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCountryByName", reflect.TypeOf((*MockRepository)(nil).FindCountryByName), ctx, name)
}

// FindSubscriptions mocks base method.
func (m *MockRepository) FindSubscriptions(ctx context.Context, userId, countryId int64, active bool) ([]*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptions", ctx, userId, countryId, active)
	ret0, _ := ret[0].([]*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptions indicates an expected call of FindSubscriptions.
func (mr *MockRepositoryMockRecorder) FindSubscriptions(ctx, userId, countryId, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptions", reflect.TypeOf((*MockRepository)(nil).FindSubscriptions), ctx, userId, countryId, active)
}

// FindUserById mocks base method.
func (m *MockRepository) FindUserById(ctx context.Context, userId int64) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserById", ctx, userId)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockRepositoryMockRecorder) FindUserById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockRepository)(nil).FindUserById), ctx, userId)
}

// GetAllCountries mocks base method.
func (m *MockRepository) GetAllCountries(ctx context.Context) ([]*entity.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCountries", ctx)
	ret0, _ := ret[0].([]*entity.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCountries indicates an expected call of GetAllCountries.
func (mr *MockRepositoryMockRecorder) GetAllCountries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCountries", reflect.TypeOf((*MockRepository)(nil).GetAllCountries), ctx)
}

// GetAllProxies mocks base method.
func (m *MockRepository) GetAllProxies(ctx context.Context) ([]*entity.Proxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProxies", ctx)
	ret0, _ := ret[0].([]*entity.Proxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProxies indicates an expected call of GetAllProxies.
func (mr *MockRepositoryMockRecorder) GetAllProxies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProxies", reflect.TypeOf((*MockRepository)(nil).GetAllProxies), ctx)
}

// GetKeyBySubscription mocks base method.
func (m *MockRepository) GetKeyBySubscription(ctx context.Context, subscriptionId int64) (*entity.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyBySubscription", ctx, subscriptionId)
	ret0, _ := ret[0].(*entity.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyBySubscription indicates an expected call of GetKeyBySubscription.
func (mr *MockRepositoryMockRecorder) GetKeyBySubscription(ctx, subscriptionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyBySubscription", reflect.TypeOf((*MockRepository)(nil).GetKeyBySubscription), ctx, subscriptionId)
}

// Initialize mocks base method.
func (m *MockRepository) Initialize(schemePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", schemePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockRepositoryMockRecorder) Initialize(schemePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockRepository)(nil).Initialize), schemePath)
}

// InsertKey mocks base method.
func (m *MockRepository) InsertKey(ctx context.Context, key entity.Key) (*entity.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertKey", ctx, key)
	ret0, _ := ret[0].(*entity.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertKey indicates an expected call of InsertKey.
func (mr *MockRepositoryMockRecorder) InsertKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertKey", reflect.TypeOf((*MockRepository)(nil).InsertKey), ctx, key)
}

// UpdateUser mocks base method.
func (m *MockRepository) UpdateUser(ctx context.Context, user *entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRepository)(nil).UpdateUser), ctx, user)
}
